### ISSUE TITLE
iOS震动模式下无声音；iOS快进无法使用；iOS无法后台播放

### ISSUE THREAD

**Issue by zw1232002** [boyan01/flutter-netease-music#101]
hi 哥们，

我在iOS真机上测试的时候发现：

1.当我把手机调整成震动，就无法播放了；
2.快进失效了
3.当应用在前台的时候，系统的音乐播放栏目和控制中心都可以控制音乐，但是应用切到后台就不行了，这个应该是注册一个权限就好了

**Comment by boyan01** [comment]
好的，感谢反馈哈。

问题 1、3  我看再去查一下相关文档吧。
问题 2 好像是功能缺失导致的，我稍后有时间修复一下。
