### ISSUE TITLE
apk

### ISSUE THREAD

**Issue by wilfried18** [boyan01/flutter-netease-music#102]
Hello
I'd like to test your application but I can't find an apk file.

**Comment by boyan01** [comment]
https://github.com/boyan01/flutter-netease-music/actions/runs/43770067

**Comment by wilfried18** [comment]
@boyan01 Thank you for your response
I can see this page, but no fair link
app-armeabi-v7a-release.apk

**Comment by ziming1** [comment]
What does the 'fair link' means? 
If you are logged in, you should see the download link on this page.
