### ISSUE TITLE
Country

### ISSUE THREAD

**Issue by mrfoxie** [boyan01/flutter-netease-music#103]
Hello i just love your app but i just want to ask you that how can i change an make it world wide

**Comment by boyan01** [comment]
Sorry, can you elaborate on your intentions? I didn't understand what you wrote above.

**Comment by mrfoxie** [comment]
i just want to say that this app allow us to play song from china country only when i try to play songs of akon etc. it tell me it not available in your country its only available in china only

**Comment by boyan01** [comment]
**The data source in the demo is not mine, but Netease's.** 

So sir, I can't help you with this.

**Comment by mrfoxie** [comment]
Okay
