### ISSUE TITLE
Error while running on iOS 

### ISSUE THREAD

**Issue by Nak9009** [boyan01/flutter-netease-music#108]
Command PhaseScriptExecution failed with a nonzero exit code .

**Comment by boyan01** [comment]
I just tried it and the build passed. 

How about try upgrading your flutter and pod versions to the latest?

**Comment by Nak9009** [comment]
Im using :
- Flutter 1.12.13+hotfix.8 • channel stable •
- Pod version 1.9.0

**Comment by boyan01** [comment]
project is not compat with flutter stable channel since 
 commit : 6def902da43461e9e1acbb888b5eea1538e7a2a0
