### ISSUE TITLE
可以试试flutter运行node，启动api服务器呢

### ISSUE THREAD

**Issue by xuelongqy** [boyan01/flutter-netease-music#111]
我fork了项目，经过多次改动才能跑起来，dart版的api貌似有些改动。可以尝试使用flutter运行node [flutter_node](https://github.com/xuelongqy/flutter_node)，来跑api服务器。已经实验过没有太大问题，[xuelongqy/flutter-netease-music](https://github.com/xuelongqy/flutter-netease-music)

**Comment by boyan01** [comment]
> 我fork了项目，经过多次改动才能跑起来

~~应该不需要多次改动吧，我这边都是能直接 run 的。~~（看了一下你的修改，确实搜索那一块懒癌发作一直没改....

>  可以尝试使用flutter运行node flutter_node

这个看起来不错啊，可能本地跑一个 node app，但是性能上会有问题么？对多平台的支持怎么样？

**Comment by xuelongqy** [comment]
> > 我fork了项目，经过多次改动才能跑起来
> 
> ~应该不需要多次改动吧，我这边都是能直接 run 的。~（看了一下你的修改，确实搜索那一块懒癌发作一直没改....
> 
> > 可以尝试使用flutter运行node flutter_node
> 
> 这个看起来不错啊，可能本地跑一个 node app，但是性能上会有问题么？对多平台的支持怎么样？

目前支持android、ios和macOS，linux和windows也支持但是没有编译，等flutter官方支持了再说吧。需要使用多线程，所以性能没什么问题，服务也只提供给本身软件，所以也不会有太大消耗，唯一的不好就是包可能会大一些

**Comment by rexuehuaqingchun** [comment]
Running "flutter pub get" in flutter-netease-music-master...             
pub get failed (66; Could not find a file named "pubspec.yaml" in "/Users/..../flutter-netease-music-master/music_service".)   还有path: loader/  ，cloud_music_api/  都无法找到，怎么样才能解决这个问题呢？

**Comment by liuchunlong1** [comment]
Running "flutter pub get" in flutter-netease-music-master...
pub get failed (66; Could not find a file named "pubspec.yaml" in "/Users/..../flutter-netease-music-master/music_service".) 还有path: loader/ ，cloud_music_api/ 都无法找到，怎么样才能解决这个问题呢？

**Comment by lylelqc** [comment]
> Running "flutter pub get" in flutter-netease-music-master...
> pub get failed (66; Could not find a file named "pubspec.yaml" in "/Users/..../flutter-netease-music-master/music_service".) 还有path: loader/ ，cloud_music_api/ 都无法找到，怎么样才能解决这个问题呢？

readme里面写了，在项目的根目录下运行：git submodule update --init --recursive

**Comment by liuqiao56** [comment]
liuqiao@liuqiaodeMacBook-Pro flutter-netease-music % flutter run
Launching lib/main.dart on iPhone 11 Pro in debug mode...

Compiler message:
lib/pages/leaderboard/page_leaderboard.dart:65:44: Error: The getter 'subtitle1' isn't defined for the class
'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart'
 ('../../../development/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'subtitle1'.
        style: Theme.of(context).textTheme.subtitle1.copyWith(fontWeight: FontWeight.w800),
主题颜色都找不到

**Comment by mksavage63** [comment]
I rap
