### ISSUE TITLE
应用在保持前台的时候手机熄屏后然后指纹开屏会闪屏一下

### ISSUE THREAD

**Issue by DreamFever** [boyan01/flutter-netease-music#112]
我写了一个应用也遇到这样的情况，我的应用在开屏时是白色，这个是红色的，貌似是splash，不知道作者有没有解决方案呢，不用指纹解锁就没有这种情况。

**Comment by boyan01** [comment]
刚才用手机试了一下，从锁屏页面会回到应用前台页面，是不会闪屏一下的。但是有下面两种情况会闪一下

1. app 主界面按 back 键，回到桌面，再点开 app，会快速的闪过一下红色。
2. app 主界面按 back 键，回到桌面，在通知栏点击音乐播放通知，屏幕会出现音乐通知的背景颜色。

第 2 点应该是三星系统的 feature。
第 1 点的话，可能是 https://github.com/boyan01/flutter-netease-music/blob/master/lib/pages/splash/page_splash.dart  这个页面引起的。暂时也没有好的处理方式。

至于你写的应用，如果开屏是白色很困扰你的话，可以将启动 activity 的背景色改为透明或者其他颜色试试。

**Comment by DreamFever** [comment]
可能是我的手机配置不太好的原因，我还发现在应用内按任务键然后按返回键回到应用会快速的闪一下黑屏，或者通过任务键切换到flutter应用（单击切换，非双击切换）也会快速闪一下黑屏，感觉是flutter的问题。

**Comment by 0x1af2aec8f957** [comment]
升级flutter的版本为2.5，该问题已被修复
