### ISSUE TITLE
运行报这个错误。

### ISSUE THREAD

**Issue by 724607039** [boyan01/flutter-netease-music#118]
/Users/zhuhongwei/flutter/bin/flutter --no-color pub get
Running "flutter pub get" in flutter-netease-music-master...     
Could not find a file named "pubspec.yaml" in "/Users/zhuhongwei/Downloads/flutter-netease-music-master/music_service".
pub get failed (66; Could not find a file named "pubspec.yaml" in "/Users/zhuhongwei/Downloads/flutter-netease-music-master/music_service".)
Process finished with exit code 66

**Comment by boyan01** [comment]
how to start 里写的很清楚哈：
```
git clone https://github.com/boyan01/flutter-netease-music.git 
git submodule update --init --recursive
```

**Comment by 724607039** [comment]
执行了这两句，然后用as打开运行 报这个错


/Users/zhuhongwei/flutter/bin/flutter --no-color pub get
Waiting for another flutter command to release the startup lock...
Running "flutter pub get" in flutter-netease-music...&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
Could not find a file named "pubspec.yaml" in "/Users/zhuhongwei/flutter-netease-music/music_service".
pub get failed (66; Could not find a file named "pubspec.yaml" in "/Users/zhuhongwei/flutter-netease-music/music_service".)
Process finished with exit code 66




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"伯言"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月28日(星期天) 晚上9:03
收件人:&nbsp;"boyan01/flutter-netease-music"<flutter-netease-music@noreply.github.com&gt;;
抄送:&nbsp;"勿忘初心"<724607039@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [boyan01/flutter-netease-music] 运行报这个错误。 (#118)





 
how to start 里写的很清楚哈：
 git clone https://github.com/boyan01/flutter-netease-music.git  git submodule update --init --recursive

**Comment by mksavage63** [comment]
> /Users/zhuhongwei/flutter/bin/flutter --no-color pub get
> 
> Running "flutter pub get" in flutter-netease-music-master...     
> 
> Could not find a file named "pubspec.yaml" in "/Users/zhuhongwei/Downloads/flutter-netease-music-master/music_service".
> 
> pub get failed (66; Could not find a file named "pubspec.yaml" in "/Users/zhuhongwei/Downloads/flutter-netease-music-master/music_service".)
> 
> Process finished with exit code 66
