### ISSUE TITLE
运行不起来 提示NDK 错误

### ISSUE THREAD

**Issue by wang625424** [boyan01/flutter-netease-music#126]
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':system_clock'.
> NDK not configured. Download it with SDK manager. Preferred NDK version is '21.0.6113669'. 

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s

环境：
# flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.20.4, on Microsoft Windows [Version
    10.0.18363.1082], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2 )
[√] Android Studio (version 4.0)
[√] VS Code (version 1.50.0)
[√] Connected device (1 available)

**Comment by boyan01** [comment]
打开 Android Studio，前往 Android SDK Manager 安装一下 21.0.6113669 版本的 NDK 应该可以解决此问题
