### ISSUE TITLE
android studio运行出错

### ISSUE THREAD

**Issue by GVousiu** [boyan01/flutter-netease-music#130]
- 当前flutter版本：1.22.3

- 执行flutter run --debug报错，报错信息如下：

> Using hardware rendering with device sdk gphone x86 arm. If you notice graphics artifacts, consider enabling software
rendering with "--enable-software-rendering".
Launching lib\main.dart on sdk gphone x86 arm in debug mode...
FAILURE: Build failed with an exception.
\* What went wrong:
Could not determine the dependencies of task ':system_clock:mergeDebugNativeLibs'.
CMake '3.10.2' was not found in PATH or by cmake.dir property.        
\* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
\* Get more help at https://help.gradle.org
BUILD FAILED in 5s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                         6.3s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by boyan01** [comment]
是不是没有安装 NDK？

安装 一下 ndk 试试呢？ https://developer.android.com/studio/projects/install-ndk

**Comment by GVousiu** [comment]
安装了的 是NDK版本不对 我把NDK版本降级为

> 21.0.6113669

就可以了

**Comment by GVousiu** [comment]
现在已经可以正常运行了 但感觉api服务是不是不太稳定 早上一直超时 吃了个饭回来就好了
