### ISSUE TITLE
运行失败！！！

### ISSUE THREAD

**Issue by 1635642612** [boyan01/flutter-netease-music#133]
Error output from Xcode build:
↳
    ** BUILD FAILED **
Xcode's output:
↳
    ../.pub-cache/hosted/pub.flutter-io.cn/overlay_support-1.0.5/lib/src/overlay.dart:156:19: Error: The method 'ancestorWidgetOfExactType' isn't defined for the class 'BuildContext'.
     - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('../Downloads/dev_soft/flutter/packages/flutter/lib/src/widgets/framework.dart').
    Try correcting the name to the name of an existing method, or defining a method named 'ancestorWidgetOfExactType'.
          if (context.ancestorWidgetOfExactType(OverlaySupport) != null) {
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
    ../.pub-cache/hosted/pub.flutter-io.cn/overlay_support-1.0.5/lib/src/overlay_entry.dart:17:37: Error: The method 'ancestorWidgetOfExactType' isn't defined for the class 'BuildContext'.

**Comment by keluokeda** [comment]
+1

**Comment by boyan01** [comment]
感谢提醒， 已修复： ee0669c267289f344bc91d8c0e11f809b348e5f0
