### ISSUE TITLE
Running "flutter pub get" in flutter-netease-music... 出错

### ISSUE THREAD

**Issue by keluokeda** [boyan01/flutter-netease-music#134]
The current Dart SDK version is 2.10.5.

Because quiet depends on overlay_support >=1.1.0-nullsafety.0 which requires SDK version >=2.12.0-0 <3.0.0, version solving failed.
pub get failed (1; Because quiet depends on overlay_support >=1.1.0-nullsafety.0 which requires SDK version >=2.12.0-0 <3.0.0, version solving failed.)
Process finished with exit code 1

**Comment by boyan01** [comment]
flutter 版本过低导致的，需要最新的 dev channel 。
