### ISSUE TITLE
com.android.tools.build:gradle:4.1.2编译不通过PlayQueue.kt

### ISSUE THREAD

**Issue by 98dsky** [boyan01/flutter-netease-music#135]
这个使用classpath "com.android.tools.build:gradle:4.1.2 会出现这个问题，如果使用classpath 'com.android.tools.build:gradle:3.5.3' 版本可以编译成功，看能不能解决，因为很多插件要求在4+以上的gradle才能编译成功
                
e: /Users/tangzhaohui/anziyihao/music_service/android/src/main/kotlin/tech/soit/quiet/player/PlayQueue.kt: (182, 19): Java type mismatch expected (Mutable)List<(raw) Any?>! but found MutableList<MusicItem /* = MusicMetadata */>. Use explicit cast
e: /Users/tangzhaohui/anziyihao/music_service/android/src/main/kotlin/tech/soit/quiet/player/PlayQueue.kt: (184, 19): Java type mismatch expected (Mutable)List<(raw) Any?>! but found kotlin.collections.ArrayList<String> /* = java.util.ArrayList<String> */. Use explicit cast
e: /Users/tangzhaohui/anziyihao/music_service/android/src/main/kotlin/tech/soit/quiet/player/PlayQueue.kt: (191, 29): Java type mismatch expected (Mutable)List<(raw) Any?>! but found MutableList<MusicItem /* = MusicMetadata */>. Use explicit cast
e: /Users/tangzhaohui/anziyihao/music_service/android/src/main/kotlin/tech/soit/quiet/player/PlayQueue.kt: (195, 17): Java type mismatch expected (Mutable)Map<(raw) Any?, (raw) Any?>! but found MutableMap<String, Any>. Use explicit cast
e: /Users/tangzhaohui/anziyihao/music_service/android/src/main/kotlin/tech/soit/quiet/player/PlayQueue.kt: (199, 57): Java type mismatch expected (Mutable)List<(raw) Any?>! but found MutableList<String>. Use explicit cast
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':music_player:compileReleaseKotlin'.         
> Compilation error. See log for more details                           
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 3m 0s

**Comment by 98dsky** [comment]
使用的是最新版本Master分支的

**Comment by 98dsky** [comment]
ext.kotlin_version = '1.4.0'

.kotlin是使用1.4.0 ，我是用官方建议的目录的形式加进去的
 music_player:
    path: music_service/
主项目使用classpath 'com.android.tools.build:gradle:4.1.2'
music_service使用 classpath 'com.android.tools.build:gradle:4.0.1'
这样子编译不通过，

如果主项目使用com.android.tools.build:gradle:3.5.3
music_service使用 classpath 'com.android.tools.build:gradle:4.0.1'
编译能通过

**Comment by boyan01** [comment]
兄弟，我刚刚试了一下，这个项目能编译通过呀。  你想问的是啥？

master 分支，环境 flutter 2.0

**Comment by 98dsky** [comment]
[✓] Flutter (Channel dev, 1.27.0-4.0.pre, on macOS 11.2.2 20D80 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.1)
[✓] VS Code (version 1.53.2)
[✓] Connected device (2 available)

**Comment by 98dsky** [comment]
我换2.0试一下

**Comment by 98dsky** [comment]
flutter-netease-music : gradle3.5.3 music_service: gradle 4.0.1 
如果都改成 flutter-netease-music gradle由3.5.3改为4.1.2或者4.0.1 能 flutter run ,但不能  flutter build apk 。
会出现以前的错误，已经是master 分支，环境 更新为flutter 2.0了

**Comment by 98dsky** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.1, on macOS 11.2.2 20D80 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.1)
[✓] VS Code (version 1.53.2)
[✓] Connected device (1 available)

**Comment by 98dsky** [comment]
简单来说，就是主项目使用 classpath "com.android.tools.build:gradle:4.1.2"，就不能编译通过。

**Comment by boyan01** [comment]
哦哦，我好像了解你说的了。目前我的主项目还是用的 3.5.3，所以能通过编译。

之前 AGP 升级过一次 4.x ，但是有些问题，就降级下来了。问题可以参见下面的链接

https://issuetracker.google.com/issues/158753935 

https://github.com/flutter/flutter/issues/58247

https://github.com/flutter/flutter/issues/58247

**Comment by 98dsky** [comment]
好好，我看看，短期还会考虑升级4.X吗

**Comment by boyan01** [comment]
刚刚试了一下，好像问题已经修复，于是我就顺手升级到 4.1.2 吧： https://github.com/boyan01/flutter-netease-music/commit/3c080575107fe8d8fb6065dab1a730c66012605a

感谢反馈哈~

**Comment by boyan01** [comment]
可以更新下代码试试，Issue 我先关闭了，如果有问题，可以随时打开。

**Comment by 98dsky** [comment]
可以了，神速，当天解决！
