### ISSUE TITLE
报错！！

### ISSUE THREAD

**Issue by RoverCcc** [boyan01/flutter-netease-music#137]
报错！！

Could not find a file named "pubspec.yaml" in "C:\Users\RoverCcc\flutter-netease-music\music_service".

pub get failed (66; Could not find a file named "pubspec.yaml" in "C:\Users\RoverCcc\flutter-netease-music\music_service".)

**Comment by boyan01** [comment]
参考： https://github.com/boyan01/flutter-netease-music#how-to-start-%E5%A6%82%E4%BD%95%E5%BC%80%E5%A7%8B

**Comment by RoverCcc** [comment]
> 参考： https://github.com/boyan01/flutter-netease-music#how-to-start-%E5%A6%82%E4%BD%95%E5%BC%80%E5%A7%8B

他这边说music service找不到yaml文件

**Comment by RoverCcc** [comment]
> 参考： https://github.com/boyan01/flutter-netease-music#how-to-start-%E5%A6%82%E4%BD%95%E5%BC%80%E5%A7%8B

请问可以给个apk吗？如果方便的话

**Comment by boyan01** [comment]
试试能不能下载Github Action 中生成的 Artifacts 呢？

 https://github.com/boyan01/flutter-netease-music/actions/runs/722005807

**Comment by RoverCcc** [comment]
> 试试能不能下载Github Action 中生成的 Artifacts 呢？
> 
>  https://github.com/boyan01/flutter-netease-music/actions/runs/722005807

感谢！！
