### ISSUE TITLE
安卓报错，帮忙看看什么问题呢？

### ISSUE THREAD

**Issue by dongjh890815** [boyan01/flutter-netease-music#138]

**Comment by dongjh890815** [comment]
* What went wrong:
Execution failed for task ':system_clock:externalNativeBuildDebug'.
> Build command failed.
  Error while executing process /Users/guokai/Library/Android/sdk/cmake/3.10.2.4988404/bin/ninja with arguments {-C /Users/guokai/.pub-cache/hosted/http%58%47%47mirrors.cnnic.cn%47dart-pub/system_clock-0.7.0/android/.cxx/cmake/debug/armeabi-v7a systemclock}
  ninja: Entering directory `/Users/guokai/.pub-cache/hosted/http%58%47%47mirrors.cnnic.cn%47dart-pub/system_clock-0.7.0/android/.cxx/cmake/debug/armeabi-v7a'
  [1/2] Building CXX object 'CMakeFiles/systemclock.dir/Users/guokai/.pub-cache/hosted/http%58%47%47mirrors.cnnic.cn%47dart-pub/system_clock-0.7.0/cpp/system_clock.cpp.o'
  FAILED: CMakeFiles/systemclock.dir/Users/guokai/.pub-cache/hosted/http%58%47%47mirrors.cnnic.cn%47dart-pub/system_clock-0.7.0/cpp/system_clock.cpp.o 
  /Users/guokai/Library/Android/sdk/ndk/21.1.6352462/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ --target=armv7-none-linux-androideabi16 --gcc-toolchain=/Users/guokai/Library/Android/sdk/ndk/21.1.6352462/toolchains/llvm/prebuilt/darwin-x86_64 --sysroot=/Users/guokai/Library/Android/sdk/ndk/21.1.6352462/toolchains/llvm/prebuilt/darwin-x86_64/sysroot  -Dsystemclock_EXPORTS -I/Users/guokai/.pub-cache/hosted/http%58%47%47mirrors.cnnic.cn%47dart-pub/system_clock-0.7.0/android/src/main/cpp/../../../../cpp/include -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -march=armv7-a -mthumb -Wformat -Werror=format-security   -O0 -fno-limit-debug-info  -fPIC -MD -MT 'CMakeFiles/systemclock.dir/Users/guokai/.pub-cache/hosted/http%58%47%47mirrors.cnnic.cn%47dart-pub/system_clock-0.7.0/cpp/system_clock.cpp.o' -MF CMakeFiles/systemclock.dir/Users/guokai/.pub-cache/hosted/http%58%47%47mirrors.cnnic.cn%47dart-pub/system_clock-0.7.0/cpp/system_clock.cpp.o.d -o 'CMakeFiles/systemclock.dir/Users/guokai/.pub-cache/hosted/http%58%47%47mirrors.cnnic.cn%47dart-pub/system_clock-0.7.0/cpp/system_clock.cpp.o' -c '/Users/guokai/.pub-cache/hosted/http%58%47%47mirrors.cnnic.cn%47dart-pub/system_clock-0.7.0/cpp/system_clock.cpp'
  depfile has multiple output paths
  ninja: build stopped: subcommand failed.

**Comment by boyan01** [comment]
没看出有什么问题，另外 CI 上的 Android 构建是正常的。
https://github.com/boyan01/flutter-netease-music/runs/2276849980

建议检查一下自己的环境呢？
https://stackoverflow.com/questions/54569963/error-building-depfile-has-multiple-output-paths-ninja-build-stopped-subcomm
