### ISSUE TITLE
Could not find a file named "pubspec.yaml"

### ISSUE THREAD

**Issue by hanhabesha** [boyan01/flutter-netease-music#141]
Could not find a file named "pubspec.yaml" in "C:\super\flutter-netease-music\music_service".
pub get failed (66; Could not find a file named "pubspec.yaml" in "C:\super\flutter-netease-music\music_service".)

**Comment by boyan01** [comment]
https://github.com/boyan01/flutter-netease-music/issues/52#issuecomment-516833294
