### ISSUE TITLE
Get dependencies报错

### ISSUE THREAD

**Issue by BPDBSIR** [boyan01/flutter-netease-music#143]
Because every version of flutter_test from sdk depends on meta 1.3.0 and json_annotation >=4.1.0 depends on meta ^1.4.0, flutter_test from sdk is incompatible with json_annotation >=4.1.0.
So, because quiet depends on both json_annotation ^4.1.0 and flutter_test any from sdk, version solving failed.
pub get failed (1; So, because quiet depends on both json_annotation ^4.1.0 and flutter_test any from sdk, version solving failed.)

本地装的Flutter SDK为2.2版本

**Comment by boyan01** [comment]
看起来 meta 版本的问题，简单改了一下： b063967591028bf7465cc730075c8e2752e2ee73  应该没问题了。

**Comment by BPDBSIR** [comment]
![image](https://user-images.githubusercontent.com/34305780/126867911-346d4a65-e088-44b3-93d8-24e5a3f05341.png)
pub get成功了，绝大部分错误都消失了，但是还是有些错误还存在

**Comment by BPDBSIR** [comment]
是不是还是因为那个json序列化包的问题

**Comment by boyan01** [comment]
> ![image](https://user-images.githubusercontent.com/34305780/126867911-346d4a65-e088-44b3-93d8-24e5a3f05341.png)
> pub get成功了，绝大部分错误都消失了，但是还是有些错误还存在

这些错误都是 lint 提示的错误，不影响编译。

（当初进行项目的时候，还没有 dart lint，有些地方写的和目前的 dart 规范不太相符符，另外上周刚把 flutter lint 引入了，所以会报不少 warning 和 error 。但这些不会影响正常的编译...

**Comment by BPDBSIR** [comment]
![image](https://user-images.githubusercontent.com/34305780/126869938-8552dd93-5ea1-4e64-b97e-3af07caa0bfc.png)
```
lib/pages/page_playing_list.dart:19:9: Error: No named parameter with the name 'constraints'.
        constraints:
        ^^^^^^^^^^^
/D:/src/flutter/packages/flutter/lib/src/material/bottom_sheet.dart:649:12: Context: Found this candidate, but the arguments don't match.
Future<T?> showModalBottomSheet<T>({
           ^^^^^^^^^^^^^^^^^^^^


FAILURE: Build failed with an exception.

* Where:
Script 'D:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1035

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'D:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 18s
Exception: Gradle task assembleDebug failed with exit code 1
```
运行的时候好像还是报了点错误

**Comment by BPDBSIR** [comment]
刚才拉了最新的代码，已经可以正常运行了
