### ISSUE TITLE
i have a bug there 

### ISSUE THREAD

**Issue by wwwworkhard** [boyan01/flutter-netease-music#144]
![image](https://user-images.githubusercontent.com/12581016/127757310-f26061be-3a76-4db0-8fd1-4f04b9aaa2d3.png)

Avoid lines longer than 80 characters.dart(lines_longer_than_80_chars)
The function 'StateNotifierProvider' isn't defined.
Try importing the library that defines 'StateNotifierProvider', correcting the name to the name of an existing function, or defining a function named 'StateNotifierProvider'.d

This bug makes it impossible to run  ，i use  flutter sdk v2.2.3   Tools • Dart 2.13.4

**Comment by boyan01** [comment]
`StateNotifierProvider` defined in flutter_riverpod, which already imported to project.

But I noticed that CI broken in https://github.com/boyan01/flutter-netease-music/runs/3209701400?check_suite_focus=true

I made a small fix in 61859358afaa5bbc2b6e55a66abbdd80f16e2e69 and CI refine now https://github.com/boyan01/flutter-netease-music/runs/3211817522 

So can you re-pull the code and try to compile it again?

**Comment by wwwworkhard** [comment]
![image](https://user-images.githubusercontent.com/12581016/127763266-e2638027-4fe5-4fb0-8664-e1d0405082d7.png)
thanks for your help.  The previous problem has been solved. but i find new bugs. 
The reason for most of the problems is parameter type error 。

**Comment by boyan01** [comment]
Yes, there is a lot of errors, but all of errors are generated by flutter_lint. They will not affect compilation at all for the time being.

The issue which is tracking this https://github.com/boyan01/flutter-netease-music/issues/142
