### ISSUE TITLE
dio

### ISSUE THREAD

**Issue by lishaoshi** [boyan01/flutter-netease-music#147]
请教下怎么没找到是用dio模块

**Comment by boyan01** [comment]
什么意思？

**Comment by lishaoshi** [comment]
就是想看看如何解决dio+loading如何耦合的，但是没看到项目里面使用dio，但是看依赖使用了

**Comment by boyan01** [comment]
嗯嗯，此项目的网易云相关的 api 都走的这个这个库：https://github.com/ziming1/NeteaseCloudMusicApi/blob/master/lib/src/util/request.dart

确实没有用到 dio ....
