### ISSUE TITLE
项目编译失败，很多属性没有

### ISSUE THREAD

**Issue by zqlq4ever** [boyan01/flutter-netease-music#151]
![微信截图_20211222113208](https://user-images.githubusercontent.com/37474811/147031106-c7176792-8349-44df-bc7b-2b5ff4cda5b4.png)

**Comment by boyan01** [comment]
CI 编译正常，请使用项目说明中的 beta  channel 进行编译。

https://github.com/boyan01/flutter-netease-music/runs/4596636672?check_suite_focus=true
