### ISSUE TITLE
收藏音乐功能无法使用

### ISSUE THREAD

**Issue by jiangxiaoqiang** [boyan01/flutter-netease-music#152]
收藏音乐功能无法使用，接口提示网络太拥挤。https://github.com/ziming1/NeteaseCloudMusicApi/issues/8

405 {msg: 操作频繁，请稍候再试, code: 405, message: 操作频繁，请稍候再试}

**Comment by boyan01** [comment]
https://github.com/Binaryify/NeteaseCloudMusicApi/issues/1151

已修复 https://github.com/boyan01/flutter-netease-music/commit/e1f912d2feb030af403f02a18f6185ba931e1fb9
