### ISSUE TITLE
可以提供一份打包好的放在release里吗？

### ISSUE THREAD

**Issue by MCredbear** [boyan01/flutter-netease-music#153]
试了下自己编译，在Linux上和安卓上都无法播放（安卓下的通知栏倒是正常的，但是最近音乐打不开）。actions里的东西已经不能下载了。

**Comment by boyan01** [comment]
开发进度比较缓慢，我很少做 release。

（现在 flutter 编译其实貌似还是很方便的，不需要手动处理依赖和修改配置什么的。

**Comment by fanchou** [comment]
有空的话，我来试下，我们的项目上线都是通过actions直接打包上线的，虽然是比较简单，但是多个平台手动弄起来还是比较繁琐的。前提是要有打tag的好习惯

**Comment by boyan01** [comment]
> 有空的话，我来试下。

欢迎呀。

**Comment by nesteiner** [comment]
@boyan01 你还是做下 release 吧，我这里不知道为什么编译错误了，解决不了  
![image](https://user-images.githubusercontent.com/46296608/170680144-90685ee9-bd92-4a9e-805c-3d6959f13185.png)

**Comment by boyan01** [comment]
https://github.com/boyan01/flutter-netease-music/releases/tag/v0.3.1
