### ISSUE TITLE
冒昧请教个问题，使用的audioplayers库播放音乐，安卓端息屏后播放大概15分钟会自动暂停

### ISSUE THREAD

**Issue by huangcs427** [boyan01/flutter-netease-music#156]
你好，不好意思，在这里提了个issue，实际上这个问题和此项目不相关，我这两周也在学习flutter，做了个本地音乐播放器，用的库是audioplayers，播放音乐后，我把屏幕关闭，会一直播放，但是播放大概15分钟后，会自动暂停，我在想是不是安卓的机制问题（ios还没设备测试），需要用类似audio_service等库在后台播放，感谢你的回复。

PS：如果你觉得冒犯了你，可随时关闭这个issue，谢谢。

**Comment by boyan01** [comment]
确认是自动暂停了么？而不是app被系统回收了？

在 Android 上需要长时间在后台进行的播放等任务的话，确实需要一个后台服务（并且这个后台服务最好绑定一个前台通知），这样被系统杀死的概率会降低很多。

**Comment by huangcs427** [comment]
> 确认是自动暂停了么？而不是app被系统回收了？

谢谢你，估计是被系统回收了（我是做前端开发的，对app的机制不熟），因为重新进来的时候tab恢复成默认的tab了，我确实没有后台服务和前台通知，因为项目刚开始，你这边有什么后台服务和前台通知的库推荐吗（目前我了解的有audio_service和flutter_local_notifications），但是audio_service和我用的audioplayers有点冲突，可能需要换一个播放器的控件了。

目前我做的demo播放音乐后，华为系统的后台，也没识别到声音播放，我想做到类似网易云音乐那种，播放音乐后，锁屏和后台的通知都有一个小型的播放器能控制的

**Comment by boyan01** [comment]
> 有什么后台服务和前台通知的库推荐吗

没有啥推荐的，因为我没用过其他的库。（包括这个项目中的音频播放也不太完善。

> 我想做到类似网易云音乐那种，播放音乐后，锁屏和后台的通知都有一个小型的播放器能控制的

在 Android 可能需要使用 [media-session](https://developer.android.com/guide/topics/media-apps/working-with-a-media-session)。 但我不确定是否有人封装了相应的 flutter plugin。

**Comment by huangcs427** [comment]
好的，谢谢你的解答，我再研究一下
