### ISSUE TITLE
构建失败

### ISSUE THREAD

**Issue by qq459114173** [boyan01/flutter-netease-music#162]
Because every version of flutter_test from sdk depends on async 2.8.2 and every version of netease_api from path depends on async ^2.9.0, flutter_test from sdk is incompatible with netease_api from path.
So, because quiet depends on both netease_api from path and flutter_test from sdk, version solving failed.
pub get failed (1; So, because quiet depends on both netease_api from path and flutter_test from sdk, version solving failed.)

**Comment by ipcjs** [comment]
要用beta版SDK构建：https://github.com/boyan01/flutter-netease-music/blob/main/.devcontainer/devcontainer.json#L2
