### ISSUE TITLE
项目运行不起来，DecoderBufferCallback报错

### ISSUE THREAD

**Issue by muzi1022** [boyan01/flutter-netease-music#226]
![截屏2023-02-06 18 37 17](https://user-images.githubusercontent.com/14195987/216950747-6c35add4-4f7a-410f-a012-69501c3fbdcc.png)
报错信息如上，请问该怎么修改

**Comment by boyan01** [comment]
flutter 版本不对。 更新一下代码，然后升级到 flutter 最新 stable 3.7.1 再试试
