### ISSUE TITLE
跑不起来，大佬求助

### ISSUE THREAD

**Issue by jsyanyang** [boyan01/flutter-netease-music#232]
![image](https://user-images.githubusercontent.com/94437201/220238943-01052943-40ca-46e3-99d3-1613c409c0b4.png)

**Comment by jsyanyang** [comment]
能不能给个pubspec-lock.yaml，好多依赖冲突

**Comment by boyan01** [comment]
> 能不能给个pubspec-lock.yaml

https://github.com/boyan01/flutter-netease-music/blob/main/pubspec.lock

> 好多依赖冲突

CI 编译是没问题的。 https://github.com/boyan01/flutter-netease-music/actions/runs/4104634776/jobs/7080380830

请使用最新的 flutter stable channel. 
```
flutter channel stable
flutter upgrade
```

**Comment by jsyanyang** [comment]
找到原因，用的git hub加速插件的地址代码不是最新的，sorry,   git clone https://gitclone.com/github.com/boyan01/flutter-netease-music.git

**Comment by jsyanyang** [comment]
![image](https://user-images.githubusercontent.com/94437201/220263019-ea28c75f-3017-4b1b-9acc-26c28d82669c.png)
大佬，这个又是什么报错
