### ISSUE TITLE
请问安卓模拟器的SDK版本有限制吗，我用的安卓33好像跑不起来

### ISSUE THREAD

**Issue by jsyanyang** [boyan01/flutter-netease-music#233]
![image](https://user-images.githubusercontent.com/94437201/220279970-e982f364-29c8-4e73-8987-36edbcb89a4e.png)

**Comment by boyan01** [comment]
已修复，与模拟器版本无关。 https://github.com/boyan01/flutter-netease-music/commit/815af0d8c1f94fee604df48ae5da794948032959
