### ISSUE TITLE
debug模式不可以运行吗 ，报错了

### ISSUE THREAD

**Issue by Yanhuoyiran** [boyan01/flutter-netease-music#234]
错误信息如下 
* What went wrong:
Execution failed for task ':music_player:compileDebugAidl'.
> A failure occurred while executing com.android.build.gradle.tasks.AidlCompile$AidlCompileRunnable
   > com.android.ide.common.process.ProcessException: Error while executing process D:\Program Files\Android\SDK\commandlinetools-win-8512546_latest\build-tools\33.0.0\aidl.exe with arguments {-pD:\Program Files\Android\SDK\commandlinetools-win-8512546_latest\platforms\android-31\framework.aidl -oD:\AndroidStudioProjects\flutter-netease-music\build\music_player\generated\aidl_source_output_dir\debug\out -ID:\AndroidStudioProjects\flutter-netease-music\flutter-music-player\android\src\main\aidl -ID:\AndroidStudioProjects\flutter-netease-music\flutter-music-player\android\src\debug\aidl -ID:\.gradle\caches\transforms-3\e0926642a7b3c7a2b3ee59a81037ecd9\transformed\media-1.6.0\aidl -ID:\.gradle\caches\transforms-3\103c12a4c619f603af31815d746ebd2c\transformed\core-1.9.0\aidl -ID:\.gradle\caches\transforms-3\70bb622348525693d8c6b184d138d6c6\transformed\versionedparcelable-1.1.1\aidl -dC:\Users\YANHUO~1\AppData\Local\Temp\aidl10029146945653906884.d D:\AndroidStudioProjects\flutter-netease-music\flutter-music-player\android\src\main\aidl\tech\soit\quiet\player\MusicMetadata.aidl}

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

**Comment by boyan01** [comment]
已修复 https://github.com/boyan01/flutter-netease-music/commit/815af0d8c1f94fee604df48ae5da794948032959
