### ISSUE TITLE
generate straight-corner qr code on login

### ISSUE THREAD

**Issue by rizutazu** [boyan01/flutter-netease-music#236]
I've tried scan round-corner qr code on latest version of official android client 8.9.32 but failed. Even wechat and alipay could scan successfully. As contrast, I scanned straight-corner qr code on web app with no problem.
I think it is a bug of official client and using straight-corner may break overall visual experience, but it has already afected user experience, since login by phone number is not available now.

**Comment by boyan01** [comment]
Thanks for feedback.  I only tested iOS client before.

Already fixed in https://github.com/boyan01/flutter-netease-music/commit/66fd736f2bd145136c284bac1d8ff0651a793df1
