### ISSUE TITLE
request error : type 'KeyParameter' is not a subtype of type 'PaddedBlockCipherParameters<CipherParameters?, CipherParameters?>' of 'params'

### ISSUE THREAD

**Issue by JacksonNing** [boyan01/flutter-netease-music#295]
![image](https://github.com/boyan01/flutter-netease-music/assets/20626566/9c3e504e-80d8-47f1-b1a3-673c65983aad)
![image](https://github.com/boyan01/flutter-netease-music/assets/20626566/3a36fe1f-f2cf-47c5-b11f-19f14d89772e)

**Comment by JacksonNing** [comment]
复现步骤首页->推荐歌单

**Comment by liunice** [comment]
我也遇到这个问题了，发现页和个人页的任何歌单打开都是报这个错

**Comment by boyan01** [comment]
已修复，感谢提醒，PR：https://github.com/boyan01/flutter-netease-music/pull/297


源依赖的修复提交：https://github.com/leocavalcante/encrypt/pull/312
