### ISSUE TITLE
兄弟,请教你一下：flutter后台播放属于和原生混合吗？怎么做呢？

### ISSUE THREAD

**Issue by Mr-Cai** [boyan01/flutter-netease-music#32]

**Comment by boyan01** [comment]
音乐播放这一部分的代码是原生的。

可以在这两个文件中看到，flutter 通过 channel 和 原生进行通信以同步播放器的状态。

https://github.com/boyan01/flutter-netease-music/blob/master/android/app/src/main/kotlin/tech/soit/quiet/service/QuietPlayerChannel.kt

https://github.com/boyan01/flutter-netease-music/blob/master/lib/service/channel_media_player.dart
