### ISSUE TITLE
No named parameter with the name 'targetWidth'.

### ISSUE THREAD

**Issue by AnglaMissYWQ** [boyan01/flutter-netease-music#34]
Compiler message:
lib/repository/netease_image.dart:78:11: Error: No named parameter with the name 'targetWidth'.
          targetWidth: key.width, targetHeight: -1);
          ^^^^^^^^^^^
org-dartlang-sdk:///flutter/lib/ui/painting.dart:1655:15: Context: Found this candidate, but the arguments don't match.
Future<Codec> instantiateImageCodec(Uint8List list, {
              ^^^^^^^^^^^^^^^^^^^^^
lib/repository/netease_image.dart:99:9: Error: No named parameter with the name 'targetWidth'.
        targetWidth: key.width, targetHeight: -1);
        ^^^^^^^^^^^
org-dartlang-sdk:///flutter/lib/ui/painting.dart:1655:15: Context: Found this candidate, but the arguments don't match.
Future<Codec> instantiateImageCodec(Uint8List list, {
              ^^^^^^^^^^^^^^^^^^^^^
Compiler failed on D:\flutter_pro\flutter-netease-music-master\lib/main.dart
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                         7.9s
Gradle task assembleDebug failed with exit code 1

**Comment by boyan01** [comment]
need switch flutter channel to  master.
```cmd
flutter channel master
flutter upgrade
```
