### ISSUE TITLE
能否把视频播放单独抽离为相对独立的组件呢？

### ISSUE THREAD

**Issue by eatbye** [boyan01/flutter-netease-music#40]
学了不少东西，能否把视频播放单独抽离为相对独立的组件呢？

**Comment by boyan01** [comment]
不太理解，相对独立的组件是指什么？方便被其他项目复用的那种么？

**Comment by eatbye** [comment]
> 不太理解，相对独立的组件是指什么？方便被其他项目复用的那种么？
是的是的

**Comment by boyan01** [comment]
我等以后用空再想想怎么封装一下吧。
