### ISSUE TITLE
每日推荐页获取数据错误

### ISSUE THREAD

**Issue by lycstar** [boyan01/flutter-netease-music#42]
Bad state:response has no Location header for redirect

**Comment by boyan01** [comment]
我这边是正常的，你看看代码是不是最新的？或者有没有开代理？

**Comment by boyan01** [comment]
网易云音乐API是不支持国外IP访问的

**Comment by lycstar** [comment]
是最新的，今天下午clone的，我看你的代码，你是把api从直接访问改成了那个开源项目网易云api的吧？

**Comment by boyan01** [comment]
嗯，是的，本地开了一个Http监听。

你可以检查一下是不是自己网络问题。

**Comment by lycstar** [comment]
其他页面都没啥问题，就这个每日推荐歌曲页面，不管是用的本地搭的环境还是我的服务器都是这个错，
![7E41FC1AC2518A627765F3F3F8564887](https://user-images.githubusercontent.com/37872392/59680428-e5d4da80-9203-11e9-8170-5b20bd15084e.jpg)

**Comment by boyan01** [comment]
一步一步理顺啊。

1. 本地撘的环境是指？
2. 你的服务器是指阿里云那种云服务器吗？
3. 都是这个错是指你使用 [NeteaseCloudMusicApi](https://github.com/Binaryify/NeteaseCloudMusicApi) 访问获取每日推荐也会出错吗？
4. 确认手机没有启用任何代理吗

**Comment by lycstar** [comment]
1.本地环境就是说我在电脑搭的api，局域网访问的
2.对
3.用局域网和云服务器的接口访问这个页面都是报这个错
4.没有开代理

**Comment by boyan01** [comment]
电脑本地搭建api，使用浏览器访问 IP:PORT/recommend/songs 可以获取到数据吗？

**Comment by lycstar** [comment]
那个是没问题的，我用postman测试过

**Comment by boyan01** [comment]
这问题有点棘手啊，我的模拟器和手机都可以正常打开这个页面。

你使用手机浏览器访问你搭建的api，/recommend/songs 接口也正常是吗？

**Comment by lycstar** [comment]
访问没问题，我先试试模拟器吧

**Comment by lycstar** [comment]
大哥，我知道什么问题了，您别生气，那个地址我忘了改成我的api地址了。
![图片2_WPS图片](https://user-images.githubusercontent.com/37872392/59685439-bf686c80-920e-11e9-8232-44352abc542e.png)

**Comment by boyan01** [comment]
原来是这个导致的啊

项目使用了 https://github.com/ziming1/NeteaseCloudMusicApi 做本地的代理,由于他的项目没有做跨域处理,所以这里手动将cookie上传上去了.

**Comment by lycstar** [comment]
对

**Comment by lycstar** [comment]
感谢您为我解答问题(❁´ω`❁)
