### ISSUE TITLE
The named parameter 'targetWidth' and 'targetHeight' isn't defined.

### ISSUE THREAD

**Issue by Alexwsc** [boyan01/flutter-netease-music#44]
The named parameter 'targetWidth' isn't defined.
The named parameter 'targetHeight' isn't defined.
在lib/repository/cached_image.dart文件中的_loadAsync方法中缺少2个定义的参数，直接clone你GitHub上的项目，VSCode打开就报这个错误

**Comment by boyan01** [comment]
需要切换flutter 到  dev 分支， 详见 #34
