### ISSUE TITLE
flutter_test from sdk is incompatible with loader 

### ISSUE THREAD

**Issue by CharlesJoyce** [boyan01/flutter-netease-music#47]
新手求教，请问下面问题怎么解决？
Running "flutter packages get" in flutter-netease-music
Because every version of flutter_test from sdk depends on async 2.1.0 and every version of loader from git depends on async ^2.2.0, flutter_test from sdk is incompatible with loader from git.
So, because quiet depends on both loader from git and flutter_test any from sdk, version solving failed.
pub get failed (1)

**Comment by boyan01** [comment]
你的 flutter channel 切换到 dev 了么？

**Comment by CharlesJoyce** [comment]
尴尬...才补完这个操作。切dev常卡死，然后来回git还原折腾了好一会儿，终于好了！谢谢大神指点！

**Comment by boyan01** [comment]
确实国外框架对国内开发者不太友好
