### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by guiyatao** [boyan01/flutter-netease-music#49]
![image](https://user-images.githubusercontent.com/12374577/60985882-e713a600-a370-11e9-8c11-ab39fb75dd3b.png)

**Comment by boyan01** [comment]
看起来像是类库报错了。 

应该是dart api接口变动引起的 https://github.com/dart-lang/co19/issues/383

**Comment by guiyatao** [comment]
已经解决了，切换到sdk 稳定版本就行了

**Comment by boyan01** [comment]
嗯，flutter前几天发布1.7.x的稳定版了。看来是时候将开发环境迁移回稳定版了。
