### ISSUE TITLE
flutter run --profile (it show message below)

### ISSUE THREAD

**Issue by Nak9009** [boyan01/flutter-netease-music#50]
Compiler message:                                                       
cloud_music_api/lib/src/util/request.dart:117:51: Error: The argument type 'Utf8Decoder' can't be assigned to the parameter type 'StreamTransformer<Uint8List, dynamic>'.
 - 'Utf8Decoder' is from 'dart:convert'.                                
 - 'StreamTransformer' is from 'dart:async'.                            
 - 'Uint8List' is from 'dart:typed_data'.                               
Try changing the type of the parameter, or casting the argument to 'StreamTransformer<Uint8List, dynamic>'.
    final content = await response.transform(utf8.decoder).join();      
                                                  ^                     
Compiler terminated unexpectedly.                                       
Running Gradle task 'assembleProfile'...                                
Running Gradle task 'assembleProfile'... Done                       9.4s
Gradle task assembleProfile failed with exit code 1

**Comment by boyan01** [comment]
What is your flutter version ?

how about update flutter version to latest stable version - 1.7.8+hotfix.3?

**Comment by Nak9009** [comment]
Im using Flutter 1.8.2.

**Comment by Nak9009** [comment]
It working now when im trying downgrade to 1.7.8+hotfix.3

**Comment by boyan01** [comment]
ok, that's fine.
