### ISSUE TITLE
先生,你好.

### ISSUE THREAD

**Issue by Fxsh** [boyan01/flutter-netease-music#51]
看了你的GIf  有播放音乐的页面，
在测试了这个代码，没有能播放音乐?

**Comment by Fxsh** [comment]
![ok2](https://user-images.githubusercontent.com/40154638/62042834-9c7ba000-b231-11e9-9957-21268041cca8.gif)

**Comment by Fxsh** [comment]
请求指教，希望可以回复.

**Comment by boyan01** [comment]
应该是可以播放音乐的，点击item的时候，log中有什么异常抛出吗？

**Comment by Fxsh** [comment]
I/flutter ( 3398): playWithList 突然想爱你,Color,慢半拍,吹梦到西洲,追寻年少的光,我们在夏枝繁茂时再见,Beautiful People (feat. Khalid),You Need To Calm Down,Never Really Over,That Girl (CORSAK Remix)
I/flutter ( 3398): playWithList token = playlist_main_newsong
E/flutter ( 3398): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method updatePlaylist on channel tech.soit.quiet/player)
E/flutter ( 3398): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:7)
E/flutter ( 3398): <asynchronous suspension>
E/flutter ( 3398): #1      PlayerController.updatePlaylist (package:text_music/service/channel_media_player.dart:230:21)
E/flutter ( 3398): #2      MusicPlayer.playWithList (package:text_music/component/player/player.dart:124:23)
E/flutter ( 3398): <asynchronous suspension>
E/flutter ( 3398): #3      MusicList.defaultOnTap.<anonymous closure> (package:text_music/pages/playlist/music_list.dart:84:13)
E/flutter ( 3398): #4      MusicTile.build.<anonymous closure> (package:text_music/pages/playlist/music_list.dart:139:45)
E/flutter ( 3398): #5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:635:14)
E/flutter ( 3398): #6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:711:32)
E/flutter ( 3398): #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter ( 3398): #8      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365:11)
E/flutter ( 3398): #9      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:312:7)
E/flutter ( 3398): #10     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter ( 3398): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
E/flutter ( 3398): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter ( 3398): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter ( 3398): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter ( 3398): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter ( 3398): #16     _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter ( 3398): #17     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter ( 3398): #18     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter ( 3398): #19     _invoke1 (dart:ui/hooks.dart:250:10)
E/flutter ( 3398): #20     _dispatchPointerDataPacket (dart:ui/hooks.dart:159:5)
E/flutter ( 3398):

**Comment by boyan01** [comment]
你运行的是 master 分支的代码么？看起来是 method channel 找不到相应的实现，audio service 分支是会有这个问题的。

**Comment by Fxsh** [comment]
找了半天，终于可以了,非常棒的项目，谢谢回复!

**Comment by boyan01** [comment]
.^_^ ~
