### ISSUE TITLE
请求每日推荐歌单/每日推荐歌曲接口时出错

### ISSUE THREAD

**Issue by ljfass** [boyan01/flutter-netease-music#53]
提示：Bad state: Response has no Location header for redirect

**Comment by ljfass** [comment]
已经登录了

**Comment by boyan01** [comment]
好的，感谢你的反馈。

**Comment by boyan01** [comment]
我登录后打开每日推荐歌曲页面，未能复现此问题。
话说你更新到最新的代码后还有这个问题么？

**Comment by ljfass** [comment]
我就是正常的请求那个接口，就报错了，但是在浏览器中访问是正常的

**Comment by boyan01** [comment]
是不是开代理了呀 ? 把代理关了试试呢？
