### ISSUE TITLE
Publish Quiet Player as a separate plugin for playing media with notifications.

### ISSUE THREAD

**Issue by xsahil03x** [boyan01/flutter-netease-music#54]
It will be very beneficial for the flutter community if you can publish the Quiet player as a separate plugin.

**Comment by boyan01** [comment]
This would be a great idea to publish player as a plugin. It's hardly to find a plugin to play Media.
 
And publishing a flutter plugin that only supports one platform is obviously irresponsible.
As you can see, Quiet' player only works in Android currently...

**Comment by xsahil03x** [comment]
It is true, but if plugin for android will be available people will surely fork and do contributions to make it work for ios too... That's what I am trying to say, people need a start.

**Comment by bardiarastin** [comment]
love to see Quiet Player as a plugin and really needed, @boyan01  I can give you team viewer access to build it also for ios

**Comment by boyan01** [comment]
all right, let me give it a try. 

for the convenience of others, it is necessary to redesign the API.  I hope I can have enough time to complete it ...

**Comment by bardiarastin** [comment]
@boyan01 
this is the list of needed things for an awesome player plugin:

1. Media Controls support - Provide events for controlling the app from a bluetooth device, the lockscreen, a notification, a smartwatch or even a car.

2. Local or network, files or streams - it would be awesome if we could feed it with url and byte arrays.

3. Casting support - Seamlessly switch to any Google Cast compatible device, supporting custom media receivers.

4. Background support - Keep playing audio even after the app is in background

5. events for [Play Completion, Position Change, buffering (with payload that how much is buffered)]

I think supporting queues can be implemented in Dart.

this project is the same for react native and it's really nice, I guess it's a good starting point:
https://github.com/react-native-kit/react-native-track-player

this would be the most awesome audio player plugin on flutter ecosystem, if you needed a mac device to test for ios please don't hesitate to getting in touch with me on a.rastin98[at]gmail.com

please let me know when you publish it at github so I can help.

so much huge thanks ❤️❤️❤️

**Comment by bardiarastin** [comment]
any progress on this?!

**Comment by xsahil03x** [comment]
@bardiarastin check this out -> https://github.com/boyan01/flutter-music-player

**Comment by bardiarastin** [comment]
@xsahil03x hmmm, I see but it is Android only...

**Comment by boyan01** [comment]
Closed due to https://github.com/boyan01/flutter-music-player/pull/8

more discussions go to https://github.com/boyan01/flutter-music-player/issues/4
