### ISSUE TITLE
播放音乐的页面 ，停留时间稍微长一点 ，发热很明显  

### ISSUE THREAD

**Issue by androidCoderxiao** [boyan01/flutter-netease-music#58]
如题 ，请问是能否优化

**Comment by boyan01** [comment]
能否提供更具体的信息呢？

手机什么型号？CPU什么？停留时间长的时候 CPU 负载如何？

**Comment by androidCoderxiao** [comment]
不好意思，刚才看到 ，我这手头有 3台测试机 三星 SG-G9200 , android 6.0.1 ； 华为P9 android 8.0 ，苹果XR ios 12.3.1 ；都会出现上述问题，页面停留3分钟左右就明显感觉很烫， 我自己把页面里的高斯模糊 BlurBackground 注释掉之后再测试发热就不是很明显了 。可能是这个位置的问题 ，但是我没找到好的办法解决 。

**Comment by boyan01** [comment]
嗯，那可能是这个问题。

猜测可能是歌曲状态不断刷新，导致高斯模糊的背景效果不断重绘，而 blur 又是一个高消耗的操作，所以手机就发热了。

解决办法的话，应该可以这么做：把 _BlurBackground 这个 Widget 从 StatelessWidget 改为 StatefulWidget，然后在其 State 对象的 didUpdateWidget 方法中做一下判断——只有数据发生改变，才 setState((){}) 更新背景图片。

最后感谢反馈哈。

**Comment by androidCoderxiao** [comment]
能否把 didUpdateWidget   里面的核心代码 简单说明一下呢 。因为我试过之后 只要回调了didUpdateWidget 函数 。widget  build 就会执行。不知道应该如何控制.感谢感谢

**Comment by boyan01** [comment]
不好意思，我记错了。

**刚看了一下API文档，didUpdateWidget 后是会马上就调用 build 函数的（也就是上我之前说的解决方案是没啥用的）。**

不过话说回来，_BlurBackground 作为一个单独的 Widget。如果数据未更新，按理来说应该不会走 rebuild 流程。（可能哪里出了差错吧）

现在时间不太够用，等有时间的话我再看看这个问题吧...

**Comment by androidCoderxiao** [comment]
好的 我自己也再看看 ，期待更新

**Comment by boyan01** [comment]
今天有时间用Android Studio profiler 工具看了一下 cpu 占用，并和之前用 kotlin 写的音乐播放器做了一个对比，发现可能是 flutter 框架的性能问题。
* Flutter
![image](https://user-images.githubusercontent.com/17426470/64858311-957de500-d659-11e9-859c-8085acb82768.png)

* natvie
![image](https://user-images.githubusercontent.com/17426470/64858170-315b2100-d659-11e9-809a-17e8e3493b8c.png)

flutter 在各种页面下（不管静止还是动态页面），CPU 占用率一直在 8% 左右降不下去，而原生APP在禁止状态下，CPU占用可以降至1%以下。

当然，这也有可能是我写代码的方式不对，导致 CPU 占用率比较高。

至于高斯模糊背景的问题。由于 flutter widget 渲染的特性，可能因为前面的 Widget 在播放动画的时候，高斯模糊背景也在实时刷新。（这种性能调教问题，先放到TODO吧，等把功能都实现了再说...

**Comment by boyan01** [comment]
对了，感谢你的反馈哈～～ :-D

**Comment by androidCoderxiao** [comment]
请问是release 模式下的数据吗 ？ 那可能真的是flutter 本身存在的性能问题。看来新东西还是存在很多问题 ，感谢您的分享

**Comment by leo20160311** [comment]
膜拜各路大神
