### ISSUE TITLE
报告了错，获取不到viewPadding

### ISSUE THREAD

**Issue by ljfass** [boyan01/flutter-netease-music#60]
The getter 'viewPadding' isn't defined for the class 'MediaQueryData'.

**Comment by boyan01** [comment]
flutter 版本信息给一下哈

**Comment by ljfass** [comment]
版本号：1.6.3

**Comment by boyan01** [comment]
先升级到 1.7.x 的 stable 版本吧，1.6 也太早了...

**Comment by ljfass** [comment]
行吧

**Comment by ljfass** [comment]
呃，顺便多问一句，你项目里使用的播放器那部分的代码，有点太复杂了，看不太懂，能简单说说吗？感谢了!

**Comment by boyan01** [comment]
播放器代码？指 flutter 还是 native 呐？

播放器无非就是拿个 controller 来控制 service 播放/暂停、切换下一曲；然后 widget 监听播放器状态，当播放器状态改变时，刷新相关的 widget。

理清上面这个大思路就行了。更细节的地方，一两句话也说不清楚...

**Comment by ljfass** [comment]
那个player_channel是还含有native的思路和写法吗

**Comment by boyan01** [comment]
player_channel 属于这个项目了 https://github.com/boyan01/flutter-music-player

flutter 目前无法播放音视频，所以肯定要与 native 交互才行的。

播放器的设计主要是采用了Android MediaSession 的架构思想。

**Comment by ljfass** [comment]
👌
