### ISSUE TITLE
找不到这个cookie_jar

### ISSUE THREAD

**Issue by gaojuanjuan** [boyan01/flutter-netease-music#61]
![image](https://user-images.githubusercontent.com/14133759/65125689-6d5eff00-da28-11e9-97bd-908547a5b9f0.png)

**Comment by duantao561** [comment]
我的也报错

**Comment by boyan01** [comment]
flutter 版本是啥呀？

**Comment by gaojuanjuan** [comment]
> flutter 版本是啥呀？

![image](https://user-images.githubusercontent.com/14133759/65135415-7a83ea00-da38-11e9-9496-3f7bba6121c0.png)

**Comment by boyan01** [comment]
我也升级到 1.9.1 的版本，发现 Android Studio 会报错，但 VS code 不会。

![image](https://user-images.githubusercontent.com/17426470/65142089-837ab880-da44-11e9-9047-d928ccf49bc5.png)

![image](https://user-images.githubusercontent.com/17426470/65142044-6e9e2500-da44-11e9-8ad3-392ef69d88a7.png)

而且项目是能正常通过编译的，所以应该不会是项目的问题。 可能 flutter plugin 与 IDEA 兼容的问题。

有时间我升级一下 dio 的版本试试。

**Comment by boyan01** [comment]
好像是 dio 的问题。

 https://github.com/flutterchina/dio/issues/451

**Comment by gaojuanjuan** [comment]
只能等他们解决了？

**Comment by gaojuanjuan** [comment]
![image](https://user-images.githubusercontent.com/14133759/65142745-f9335400-da45-11e9-94a5-86090a9171b9.png)
能告诉我一下这个界面对应的是那个界面吗？

**Comment by boyan01** [comment]
是的，也可能是 Android Studio 的问题。

页面对应的是：
https://github.com/boyan01/flutter-netease-music/blob/master/lib/pages/player/page_playing.dart

**Comment by boyan01** [comment]
可以将flutter 切换到 1.7.x 的 stable 版本试试

**Comment by gaojuanjuan** [comment]
好的
