### ISSUE TITLE
pubspec.yaml有问题吧

### ISSUE THREAD

**Issue by HpBoss** [boyan01/flutter-netease-music#63]
![image](https://user-images.githubusercontent.com/39408465/65431445-13a56d00-de4c-11e9-83f9-21ab87e3064e.png)
我删除了里面的^符号，还是运行不了，还是同样的问题，请问怎么解决啊

**Comment by boyan01** [comment]
参见 Readme **How to start** 章节。
```
git clone https://github.com/boyan01/flutter-netease-music.git 
git submodule update --init --recursive
```

**Comment by HpBoss** [comment]
![image](https://user-images.githubusercontent.com/39408465/65477618-708b3c80-deb9-11e9-8dea-f85e900f6e1b.png)
之前的问题是解决饿了，但是还有其它的问题，我的flutter版本也是最新的

**Comment by boyan01** [comment]
执行 `flutter build apk` 输出什么？

**Comment by HpBoss** [comment]
![image](https://user-images.githubusercontent.com/39408465/65477757-dc6da500-deb9-11e9-9a6b-041d72861d60.png)
这个

**Comment by boyan01** [comment]
在此**工程目录下执行**哈，这个是编译项目成apk的命令。

**Comment by HpBoss** [comment]
sorry！激动了

**Comment by HpBoss** [comment]
只有一些警告了，没有错误了，在执行命令后还是要重新打开一下才行，阿里嘎多！

**Comment by boyan01** [comment]
躲一塔西吗西忒

**Comment by HpBoss** [comment]
？？？？？？

**Comment by boyan01** [comment]
日语中不客气的发音

**Comment by HpBoss** [comment]
学到了。。。。。。
