### ISSUE TITLE
台灣手機號無法登入

### ISSUE THREAD

**Issue by eeezzz** [boyan01/flutter-netease-music#64]
![2019-09-24_01h24_42](https://user-images.githubusercontent.com/4696832/65447964-4fe7c600-de6a-11e9-829d-20caaab66950.png)

請問我是用台灣手機號註冊的。

在用這手機登入時，API發生底下的錯誤。
或許是台灣手機傳入的格式不同，也或許是要呼叫另一個API。
請求協助。感恩。

```
class WelcomeRepository {
  ///检测手机号是否已存在
  static Future<Result<PhoneCheckResult>> checkPhoneExist(String phone) async {
    print('phone: $phone');
    final result = await neteaseRepository.doRequest(
      '/cellphone/existence/check',
      {'phone': phone},
    );
    if (result.isError) return result.asError;
    final value = PhoneCheckResult.fromJsonMap(result.asValue.value);
    return Result.value(value);
  }
}
```
I/flutter (17551): phone: 918122223
I/flutter (17551): request[200] : /cellphone/existence/check?param=no9qDvNCfjO%2B9m5zfvpnuGeAngcoM5rmWc8lrOmakig%3D
E/flutter (17551): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The getter 'value' was called on null.
E/flutter (17551): Receiver: null

**Comment by boyan01** [comment]
已修复
