### ISSUE TITLE
Because quiet depends on dio >=3.0.0-dev.1 which requires SDK version >2.4.0 <3.0.0, version solving failed.

### ISSUE THREAD

**Issue by wjryours** [boyan01/flutter-netease-music#65]
按照流程把代码拉了下来，为什么安装依赖安装不成功，是因为Dart SDK的版本问题还是dio这个库因为国内网络的问题访问的国内镜像不是最新的版本么？
![image](https://user-images.githubusercontent.com/25095045/65571022-be757280-df95-11e9-86b7-f3a9c3b011ec.png)
flutter doctor 一切正常
![image](https://user-images.githubusercontent.com/25095045/65571115-0b594900-df96-11e9-8c81-66675001649c.png)

**Comment by boyan01** [comment]
升级 flutter 到 1.9+ 的版本吧。

**Comment by wjryours** [comment]
你好，再请教下，问下手机号码登录报错呢..
![image](https://user-images.githubusercontent.com/25095045/65577184-ea98ef80-dfa5-11e9-903c-e07d406b3682.png)

**Comment by boyan01** [comment]
再更新一下代码试试吧。

好像是 dio 的问题，我刚在上一个提交修复了此问题。

**Comment by wjryours** [comment]
你是见过github处理问题最快的作者，点个赞
