### ISSUE TITLE
退出应用，再进就一直卡在欢迎页，报错信息如下

### ISSUE THREAD

**Issue by cxmmxc** [boyan01/flutter-netease-music#67]
I/ExoPlayerImpl(30023): Init 533565a [ExoPlayerLib/2.10.1] [dipper, MI 8, Xiaomi, 28]
E/flutter (30023): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: SocketException: Failed to create server socket (OS Error: The shared flag to bind() needs to be `true` if binding multiple times on the s
ame (address, port) combination.), address = localhost, port = 3000
E/flutter (30023): #0      _NativeSocket.bind (dart:io-patch/socket_patch.dart:605)
E/flutter (30023): <asynchronous suspension>
E/flutter (30023): #1      _RawServerSocket.bind (dart:io-patch/socket_patch.dart:1222)
E/flutter (30023): #2      _ServerSocket.bind (dart:io-patch/socket_patch.dart:1482)
E/flutter (30023): #3      ServerSocket.bind (dart:io-patch/socket_patch.dart:1473)
E/flutter (30023): #4      _HttpServer.bind (dart:_http/http_impl.dart:2590)
E/flutter (30023): #5      HttpServer.bind (dart:_http:227)
E/flutter (30023): #6      startServer (package:netease_music_api/netease_cloud_music.dart:23)
E/flutter (30023): #7      main (package:quiet/main.dart:26)
E/flutter (30023): #8      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:229)
E/flutter (30023): #9      _rootRun (dart:async/zone.dart:1124)
E/flutter (30023): #10     _CustomZone.run (dart:async/zone.dart:1021)
E/flutter (30023): #11     _runZoned (dart:async/zone.dart:1516)
E/flutter (30023): #12     runZoned (dart:async/zone.dart:1500)
E/flutter (30023): #13     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:221)
E/flutter (30023): #14     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305)
E/flutter (30023): #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172)
E/flutter (30023):
D/MusicPlayerService$MediaControllerCallback(30023): (MusicPlayerService.kt:280)MusicPlayerService$MediaControllerCallback.onMetadataChanged: onMetadataChanged : null
D/MusicPlayerService(30023): (MusicPlayerService.kt:261)MusicPlayerService.onGetRoot: on get root : /
D/MusicPlayerPlugin$connectCallback$1(30023): (MusicPlayerPlugin.kt:61)MusicPlayerPlugin$connectCallback$1.onConnected: connected , android.support.v4.media.session.MediaSessionCompat$Token@1ac4da0
I/AlarmService(30023): setBackgroundFlutterView tried to overwrite an existing FlutterNativeView

**Comment by boyan01** [comment]
已修复，更新下代码试试吧

**Comment by cxmmxc** [comment]
还是不行啊大兄弟，我看你提交的是删除了两个print。

**Comment by boyan01** [comment]
git submodule update 一下呢？

**Comment by cxmmxc** [comment]
> git submodule update 一下呢？

可以了，666！大赞
