### ISSUE TITLE
没有跑起来

### ISSUE THREAD

**Issue by zzdota** [boyan01/flutter-netease-music#69]
![image](https://user-images.githubusercontent.com/16704305/65676811-1d64e580-e083-11e9-845c-4f4d26da1814.png)
当前AS Flutter版本

不能正常跑起来,如图
![image](https://user-images.githubusercontent.com/16704305/65676914-46857600-e083-11e9-9983-bb8e40c1a88c.png)

**Comment by boyan01** [comment]
再看看 readme 上的运行说明
