### ISSUE TITLE
为什么我安装最新的SDK无法运行呢？

### ISSUE THREAD

**Issue by paddingC** [boyan01/flutter-netease-music#78]
Running "flutter pub get" in flutter-netease-music...           
Got socket error trying to find package mockito at https://pub.dartlang.org.

**Comment by boyan01** [comment]
检查一下网络环境

**Comment by paddingC** [comment]
网络环境应该没问题，就是引入包的时候提示错误，不知道什么原因
![image](https://user-images.githubusercontent.com/28521120/67373019-75730700-f5b1-11e9-95b5-ae23533a44fe.png)

**Comment by boyan01** [comment]
socket error 就是网络错误。

建议看看 flutter 怎么配置镜像或者代理的文章
