### ISSUE TITLE
hi,音乐播放功能是自己开发的？还是三方的呢

### ISSUE THREAD

**Issue by yusheng-jia** [boyan01/flutter-netease-music#80]
music_service 是负责音乐播放的吧

**Comment by boyan01** [comment]
自己开发的

代码在这个库中： https://github.com/boyan01/flutter-music-player

**Comment by yusheng-jia** [comment]
> 自己开发的
> 
> 代码在这个库中： https://github.com/boyan01/flutter-music-player

Thanks♪(･ω･)ﾉ
