### ISSUE TITLE
我在run项目是遇到了这个问题

### ISSUE THREAD

**Issue by 15128238220** [boyan01/flutter-netease-music#85]
Launching lib/main.dart on iPhone 11 Pro in debug mode...
 
Running pod install...                                                 1.8s
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target
      `Pods-Runner`: (``)

    Fetching external sources
    -> Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
    -> Fetching podspec for `music_player` from
    `.symlinks/plugins/music_player/ios`
    [!] No podspec found for `music_player` in
    `.symlinks/plugins/music_player/ios`

    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/ext
    ernal_sources/path_source.rb:14:in `block in fetch'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/use
    r_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/ext
    ernal_sources/path_source.rb:11:in `fetch'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/ins
    taller/analyzer.rb:901:in `fetch_external_source'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/ins
    taller/analyzer.rb:880:in `block (2 levels) in
    fetch_external_sources'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/ins
    taller/analyzer.rb:879:in `each'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/ins
    taller/analyzer.rb:879:in `block in fetch_external_sources'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/use
    r_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/ins
    taller/analyzer.rb:878:in `fetch_external_sources'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/ins
    taller/analyzer.rb:117:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/ins
    taller.rb:410:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/ins
    taller.rb:234:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/use
    r_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/ins
    taller.rb:233:in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/ins
    taller.rb:156:in `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/com
    mand/install.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.r
    b:334:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/com
    mand.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/bin/pod:55:in
    `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'

Error running pod install
Error launching application on iPhone 11 Pro.

**Comment by boyan01** [comment]
目前项目不支持 iOS .

**Comment by 15128238220** [comment]
仅仅在本地iOS模拟器上也不行吗

**Comment by boyan01** [comment]
这个版本可以通过 iOS 编译，但也不支持音频播放功能。
https://github.com/boyan01/flutter-netease-music/releases/tag/v0.2

**Comment by 15128238220** [comment]
好的

**Comment by boyan01** [comment]
因为现在 audio player 的 ios 部分没写，所以 iOS 编译不过。

**Comment by 15128238220** [comment]
明白了，加油
