### ISSUE TITLE
Android 打包apk 后运行报错？

### ISSUE THREAD

**Issue by yusheng-jia** [boyan01/flutter-netease-music#89]
使用命令：flutter build apk，

**Comment by boyan01** [comment]
log 都不贴一下的吗？

**Comment by yusheng-jia** [comment]
> log 都不贴一下的吗？
不好意思，忘记贴了：
12-19 16:11:52.605  6037  6147 E flutter : [ERROR:flutter/shell/common/shell.cc(178)] Dart Error: Unhandled exception:
12-19 16:11:52.605  6037  6147 E flutter : NoSuchMethodError: No top-level getter 'playerBackgroundService' declared.
12-19 16:11:52.605  6037  6147 E flutter : Receiver: top-level
12-19 16:11:52.605  6037  6147 E flutter : Tried calling: playerBackgroundService
12-19 16:11:52.605  6037  6147 E flutter : #0      NoSuchMethodError._throwNew (dart:core-patch/errors_patch.dart:200)
12-19 16:11:52.605  6037  6147 E flutter : [ERROR:flutter/runtime/dart_isolate.cc(459)] Could not resolve main entrypoint function.
12-19 16:11:52.605  6037  6147 E flutter : [ERROR:flutter/shell/common/engine.cc(195)] Could not run the isolate.
12-19 16:11:52.605  6037  6147 E flutter : [ERROR:flutter/shell/common/engine.cc(127)] Engine not prepare and launch isolate.
12-19 16:11:52.605  6037  6147 E flutter : [ERROR:flutter/shell/common/shell.cc(407)] Could not launch engine with configuration.

**Comment by boyan01** [comment]
好，感谢反馈。看起来是 flutter 的 api 又又又又变了

**Comment by yusheng-jia** [comment]
> 好，感谢反馈。看起来是 flutter 的 api 又又又又变了，周末有时间再看一下...

我问一个问题哈，为什么播放列表只加载10条，可以修改为加载整个专辑的吗？

**Comment by yusheng-jia** [comment]
> 好，感谢反馈。看起来是 flutter 的 api 又又又又变了，周末有时间再看一下...

用最新版本flutter 可以打包切运行正常了，谢谢 有个新问题，我重新提issue了
