### ISSUE TITLE
大佬能帮我优化下app ui么

### ISSUE THREAD

**Issue by lcc052772** [boyan01/flutter-netease-music#96]
我这边手头有个小型写作app，flutter做的，material design风格。ui细节可能需要优化。如果您有兴趣的话，可以进一步沟通。

**Comment by boyan01** [comment]
实不相瞒，flutter 文本编辑这一块处处都是大坑。另外我也没足够时间哈，可能帮不了你。

**Comment by lcc052772** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    文本编辑，您指的是编辑器么？编辑器确实很烦，我们正在想办法解决呢。以后有机会或许，您可以帮我们优化ui，这对你估计难度不大。我们是做的material design风格。
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                lgy052772
                            
                    
                        
                            
                                    lgy052772@gmail.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    在2020年01月17日 16:14，伯言<notifications@github.com> 写道： 


实不相瞒，flutter 文本编辑这一块处处都是大坑。另外我也没足够时间哈，可能帮不了你。



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by boyan01** [comment]
优化 UI 是指什么？ 是指没法实现设计图中的效果 ？ 还是指没有设计图，且现在 UI 不太好看，需要一个人对其重新设计且优化？

**Comment by lcc052772** [comment]
我们会提供图纸，希望您按material design风格来优化呈现效果吧，可以理解为实现图中的效果，尽管图纸可能也有瑕疵。

伯言 <notifications@github.com> 于2020年1月17日周五 下午4:25写道：

**Comment by lcc052772** [comment]
您可以考虑下么

国家社会主义华夏工人党 <lgy052772@gmail.com> 于2020年1月17日周五 下午5:32写道：

**Comment by boyan01** [comment]
不好意思，近一段时间实在很忙，抽不出时间来做兼职，所以先不考虑了。

**Comment by lcc052772** [comment]
年后也可以的

伯言 <notifications@github.com> 于2020年1月18日周六 下午3:31写道：
